### ISSUE TITLE
Impossible to import (and use) Dialogflow

### ISSUE THREAD

**Issue by tsigit** [googleapis/python-dialogflow#109]
Hi all there!

Below details about my issue - Anybody can help on fixing it please, help!

#### Environment details

  - OS: Win10-64Bit
  - Python version: 3.6.2
  - pip version: 18.1
  - `dialogflow` version: 0.5.1

#### Steps to reproduce

  1. `import dialogflow` 
_(be it from interactive python, or from Windows terminal, thqt is call from within another .py file)_
  
 2. returning the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\r.tsiresi\AppData\Local\Programs\Python\Python36\lib\site-packages\dialogflow\__init__.py", line 17, in <module>
    from dialogflow_v2 import AgentsClient
  File "C:\Users\r.tsiresi\AppData\Local\Programs\Python\Python36\lib\site-packages\dialogflow_v2\__init__.py", line 17, in <module>
    from dialogflow_v2 import types
  File "C:\Users\r.tsiresi\AppData\Local\Programs\Python\Python36\lib\site-packages\dialogflow_v2\types.py", line 20, in <module>
    from google.api import http_pb2
  File "C:\Users\r.tsiresi\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api\http_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x15google/api/http.proto\x12\ngoogle.api\"T\n\x04Http\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.google.api.HttpRule\x12\'\n\x1f\x66ully_decode_reserved_expansion\x18\x02 \x01(\x08\"\x81\x02\n\x08HttpRule\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\r\n\x03get\x18\x02 \x01(\tH\x00\x12\r\n\x03put\x18\x03 \x01(\tH\x00\x12\x0e\n\x04post\x18\x04 \x01(\tH\x00\x12\x10\n\x06\x64\x65lete\x18\x05 \x01(\tH\x00\x12\x0f\n\x05patch\x18\x06 \x01(\tH\x00\x12/\n\x06\x63ustom\x18\x08 \x01(\x0b\x32\x1d.google.api.CustomHttpPatternH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x15\n\rresponse_body\x18\x0c \x01(\t\x12\x31\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x14.google.api.HttpRuleB\t\n\x07pattern\"/\n\x11\x43ustomHttpPattern\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\tBj\n\x0e\x63om.google.apiB\tHttpProtoP\x01ZAgoogle.golang.org/genproto/googleapis/api/annotations;annotations\xf8\x01\x01\xa2\x02\x04GAPIb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

#### resolution attempted
- switching to other versions of dialogflow (down to 0.2.0) >> All attempts KO
- switching to other versions of google-api-core >> All attempts KO
- trying all kind of import (interactive or from Windows shell) from all the changes above >> All attempts KO

Any solution for solving this issue are all welcome :)

Thanks in advance!

**Comment by tsigit** [comment]
Not sure if this is the ultimate solution, but commenting all lines where `serialized_options` poped-up resolved my issue above...

**Comment by sduskis** [comment]
@googleapis/yoshi-python, can anyone help with this?

**Comment by tseaver** [comment]
I cannot reproduce the traceback:

```bash
$ python3.6 -m venv /tmp/df-p-c-v2/109
$ /tmp/df-p-c-v2/109/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-18.1 setuptools-40.6.2
$ /tmp/df-p-c-v2/109/bin/pip install dialogflow
...
Successfully installed cachetools-3.0.0 certifi-2018.11.29 chardet-3.0.4 dialogflow-0.5.1 google-api-core-1.6.0 google-auth-1.6.1 googleapis-common-protos-1.5.5 grpcio-1.17.0 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.7 requests-2.20.1 rsa-4.0 six-1.11.0 urllib3-1.24.1
$ /tmp/df-p-c-v2/109/bin/python -c "import dialogflow; print(dialogflow.__path__)"
['/tmp/df-p-c-v2/109/lib/python3.6/site-packages/dialogflow']
```

@tsigit I suspect that one or more of the dependencies is out of date. Can you please show the output from `pip freeze' in the environment where you see the traceback?

**Comment by crwilcox** [comment]
To be sure this wasn't a Windows specific issue I tried from a Win10 machine with python 3.7.1 installed and all is well. Below is the output of pip freeze on a fresh install. 

```

C:\Users\USERNAME>py -3 -m pip freeze
cachetools==3.0.0
certifi==2018.11.29
chardet==3.0.4
dialogflow==0.5.1
google-api-core==1.6.0
google-auth==1.6.1
googleapis-common-protos==1.5.5
grpcio==1.17.0
idna==2.7
protobuf==3.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pytz==2018.7
requests==2.20.1
rsa==4.0
six==1.11.0
urllib3==1.24.1
```

**Comment by tsigit** [comment]
> 
> 
> I cannot reproduce the traceback:
> 
> ```shell
> $ python3.6 -m venv /tmp/df-p-c-v2/109
> $ /tmp/df-p-c-v2/109/bin/pip install --upgrade setuptools pip
> ...
> Successfully installed pip-18.1 setuptools-40.6.2
> $ /tmp/df-p-c-v2/109/bin/pip install dialogflow
> ...
> Successfully installed cachetools-3.0.0 certifi-2018.11.29 chardet-3.0.4 dialogflow-0.5.1 google-api-core-1.6.0 google-auth-1.6.1 googleapis-common-protos-1.5.5 grpcio-1.17.0 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.7 requests-2.20.1 rsa-4.0 six-1.11.0 urllib3-1.24.1
> $ /tmp/df-p-c-v2/109/bin/python -c "import dialogflow; print(dialogflow.__path__)"
> ['/tmp/df-p-c-v2/109/lib/python3.6/site-packages/dialogflow']
> ```
> 
> @tsigit I suspect that one or more of the dependencies is out of date. Can you please show the output from `pip freeze' in the environment where you see the traceback?

@tseaver >> please see below the environment
`C:\Users\username>py -m pip freeze
absl-py==0.1.10
apiclient==1.0.3
bleach==1.5.0
bokeh==0.12.14
cachetools==3.0.0
certifi==2018.10.15
chardet==3.0.4
cycler==0.10.0
cymem==2.0.2
cytoolz==0.9.0.1
dialogflow==0.5.1
dill==0.2.8.2
discovery==0.0.4
google-api-core==1.5.2
google-api-python-client==1.7.4
google-auth==1.6.1
google-auth-httplib2==0.0.3
googleapis-common-protos==1.5.5
graphviz==0.8.2
grpcio==1.16.1
h5py==2.7.1
html5lib==0.9999999
httplib2==0.12.0
idna==2.7
IMAPClient==2.1.0
Jinja2==2.10
Keras==2.1.4
kiwisolver==1.0.1
lightgbm==2.1.2
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==1.0.1
nltk==3.2.5
numpy==1.15.4+mkl
oauth2client==2.0.0
packaging==17.1
pandas==0.22.0
plac==0.9.6
preshed==2.0.1
protobuf==3.5.1
psycopg2==2.7.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pydot==1.2.4
pyparsing==2.2.0
pyreadline==2.1
python-dateutil==2.7.0
pytz==2018.3
PyYAML==3.12
pyzmail36==1.0.3
regex==2018.1.10
requests==2.5.0
rsa==4.0
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
six==1.11.0
spacy==2.0.16
SQLAlchemy==1.2.14
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
thinc==6.12.0
toolz==0.9.0
tornado==5.0.1
tqdm==4.28.1
ujson==1.35
uritemplate==3.0.0
urllib3==1.24.1
uuid==1.30
Werkzeug==0.14.1
wrapt==1.10.11
xgboost==0.7`

**Comment by tgmerritt** [comment]
I'm seeing this issue as well - my `pip freeze` output:

Using virtualenv as depicted at the console prompt - have only installed packages necessary for my small project.  Outside of 'requests' and Flask itself, everything is either native to Python 3.7.2 or was installed with `pip install dialogflow`

Offending output from Flask:

```
    import dialogflow_v2 as dialogflow
ModuleNotFoundError: No module named 'dialogflow_v2'
```

```
(orchestration_in_python_with_dialogflow) ➜  orchestration_in_python git:(master) ✗ pip freeze
attrs==19.3.0
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
dialogflow==0.7.2
emit==0.4.0
Flask==1.1.1
google-api-core==1.16.0
google-auth==1.11.2
googleapis-common-protos==1.51.0
grpcio==1.27.2
idna==2.9
importlib-metadata==1.5.0
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
more-itertools==8.2.0
packaging==20.3
pluggy==0.13.1
protobuf==3.11.3
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.6
pytest==5.3.5
pytz==2019.3
requests==2.23.0
rsa==4.0
six==1.14.0
urllib3==1.25.8
wcwidth==0.1.8
Werkzeug==1.0.0
zipp==3.1.0
```

**Comment by busunkim96** [comment]
I am also unable to reproduce this. @tgmerritt, could you try that in a clean virtualenv?

```py
python3 -m venv env
source env/bin/activate
python3 -m pip install dialogflow
```

**Comment by HansPeterMaxwell** [comment]
> I'm seeing this issue as well - my `pip freeze` output:
> 
> Using virtualenv as depicted at the console prompt - have only installed packages necessary for my small project. Outside of 'requests' and Flask itself, everything is either native to Python 3.7.2 or was installed with `pip install dialogflow`
> 
> Offending output from Flask:
> 
> ```
>     import dialogflow_v2 as dialogflow
> ModuleNotFoundError: No module named 'dialogflow_v2'
> ```
> 
> ```
> (orchestration_in_python_with_dialogflow) ➜  orchestration_in_python git:(master) ✗ pip freeze
> attrs==19.3.0
> cachetools==4.0.0
> certifi==2019.11.28
> chardet==3.0.4
> Click==7.0
> dialogflow==0.7.2
> emit==0.4.0
> Flask==1.1.1
> google-api-core==1.16.0
> google-auth==1.11.2
> googleapis-common-protos==1.51.0
> grpcio==1.27.2
> idna==2.9
> importlib-metadata==1.5.0
> itsdangerous==1.1.0
> Jinja2==2.11.1
> MarkupSafe==1.1.1
> more-itertools==8.2.0
> packaging==20.3
> pluggy==0.13.1
> protobuf==3.11.3
> py==1.8.1
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pyparsing==2.4.6
> pytest==5.3.5
> pytz==2019.3
> requests==2.23.0
> rsa==4.0
> six==1.14.0
> urllib3==1.25.8
> wcwidth==0.1.8
> Werkzeug==1.0.0
> zipp==3.1.0
> ```

hey, me too, so can you fix it ?

**Comment by vonmoraes** [comment]
Something similar happen here. 
I solve it using python in virtualenv and running this for installing dialogflow and google-api:

```
pip install google-api-python-client
pip install dialogflow
```

my actual requirements.txt 

> dialogflow==1.0.0
> google-api-python-client==1.10.0

**Comment by busunkim96** [comment]
Closing due to inactivity. If you are still experiencing this problem, please open a issue.
