### ISSUE TITLE
Gevent monkey patchall() is not working with the dialogflog 

### ISSUE THREAD

**Issue by davit555** [googleapis/python-dialogflow#135]
Traceback (most recent call last):
  File "/home/davit/venvs/venvs/hoory_ml_3.6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/davit/venvs/venvs/hoory_ml_3.6/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/davit/venvs/venvs/hoory_ml_3.6/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1562601694.445719928","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"Thanks!

**Comment by b-loved-dreamer** [comment]
We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing ```dialogflow```. This issue may no longer be relevant. I am also unclear as to wether this is a feature request and for these reasons I am closing this issue. Please reopen if needed.
