### ISSUE TITLE
App not working on Heroku Platform

### ISSUE THREAD

**Issue by Vidushics015** [googleapis/python-dialogflow#138]
I have created a Flask-SocketIO app which is using detect_intent API. The app works fine on localhost but gives below error when deployed on Heroku:

##################
2019-08-07T04:58:50.839303+00:00 heroku[router]: at=info method=GET path="/get?msg=hi&sess=4f6f51e3ee5140a7a3c0fe37450d5a0c" host=******** fwd="********" dyno=web.1 connect=1ms service=20008ms status=500 bytes=238 protocol=https
2019-08-07T04:58:50.838162+00:00 app[web.1]: 2019-08-07 04:58:50 [10] [ERROR] Error handling request
2019-08-07T04:58:50.838177+00:00 app[web.1]: Traceback (most recent call last):
2019-08-07T04:58:50.838181+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_rema
2019-08-07T04:58:50.838183+00:00 app[web.1]: return callable_(*args, **kwargs)
2019-08-07T04:58:50.838186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
2019-08-07T04:58:50.838189+00:00 app[web.1]: return _end_unary_response_blocking(state, call, False, None)
2019-08-07T04:58:50.838191+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_bloc
2019-08-07T04:58:50.838194+00:00 app[web.1]: raise _Rendezvous(state, None, None, deadline)
2019-08-07T04:58:50.838196+00:00 app[web.1]: grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
2019-08-07T04:58:50.838197+00:00 app[web.1]: status = StatusCode.UNAVAILABLE
2019-08-07T04:58:50.838200+00:00 app[web.1]: details = "Deadline Exceeded"
2019-08-07T04:58:50.838203+00:00 app[web.1]: debug_error_string = "{"created":"@1565153930.836839962","description":"Deadline Exceeded","file":"src/core/exgrpc_status":14}"

##################

Any help would be appreciated.

**Comment by busunkim96** [comment]
Hi @Vidushics015. Would it be possible to see the relevant parts of your code? How are you providing credentials?

**Comment by Vidushics015** [comment]
Hi,

Please find the code snippets:
Flask-SocketIO config
-----------------------------------------------------------
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secretkey'
app.config['DEBUG'] = True
socketio = SocketIO(app)
users = {}

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('my event')
def handle_my_custom_event(json):
    print('received something' +str(json))
    print("###############################")
    print(request.sid)
    print("###############################")
    #return request.sid
    k = request.sid
    socketio.emit('server response', k)      #to client-side
    #@socketio.on('message from user', namespace='/messages')

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected #########'+request.sid)

@app.route("/get" , methods=['GET'])
def get_bot_response():
    userText = request.args.get('msg')
    id = request.args.get('sess')
    print('#########'+str(request.args.get('sess')))
    #print("^^^^^^^^^^^^")
    return str(detect_intent(userText,id))

Dialogflow API
-------------------------------------------------------------
def detect_intent(text, session_id):
    #print("(((((((((HEloGHelogHeloGHeloG))))))))))))))))))))))")
    language_code = 'en'
    project_id = 'newagent-viqqeo'
    #os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:\\Users\\Desktop\\NewAg.json'
    #credentials = os.environ['GOOGLE_APPLICATION_CREDENTIALS']
    #os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:\\Users\\PycharmProjects\\socketio\\credentials.json'
    #credentials_path  = "credentials.json"
    #os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = credentials_path
    session_client = dialogflow.SessionsClient()
    session = session_client.session_path(project_id, session_id)
    text_input = dialogflow.types.TextInput(text=text, language_code=language_code)
    query_input = dialogflow.types.QueryInput(text=text_input)
    response = session_client.detect_intent(session=session, query_input=query_input)
    if response.query_result.action == "email":
	........
	else:
        response = response.query_result.fulfillment_text
    #print(response)
    return response

---------------------------------------------------------------
To provide the credentials, I have used the following link:
https://github.com/elishaterada/heroku-google-application-credentials-buildpack

As you can see I tried numerous ways to provide the credentials but eventually the link worked and then i didn't get the credentials error.

But now I am getting the Deadline exceeded error. Your help is much appreciated.

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant. Now closing this issue. Please reopen if needed.
